dependencies:
  - jupyterlab==1.1.4
  - matplotlib
  - gmaps
  - numpy
  - scipy
  - pandas
  - xarray
  - netCDF4
  - fabric2
  - nbgitpuller
  - xlrd
  - seaborn
  - bs4
  - parse
  - pyyaml
  - shapely[vectorized]
  - psycopg2
  - google.api.core
  - google.cloud
  - google.cloud.storage
  - lxml
  - ipywidgets
