dependencies:
  - jupyterhub==0.9.6 
  - jupyterlab==1.1.4
  - matplotlib
  - numpy
  - scipy
  - pandas
  - xarray
  - netCDF4
  - nbgitpuller
  - xlrd
  - seaborn
  - parse
  - pyyaml
  - shapely[vectorized]
  - psycopg2
  - lxml
  - ipywidgets
  - cdsapi
