#! /bin/bash
pip install google.api.core
pip install google.cloud
pip install bs4
pip install google.cloud.storage
pip install fabric2
jupyter nbextension enable --py widgetsnbextension
jupyter labextension install @jupyter-widgets/jupyterlab-manager --debug
pip install gmaps==0.9.0
jupyter lab build --minimize=False
